# Usage: cmake -DSOURCE_DIR=... -DOUTPUT_FILE=... -P GenerateNotices.cmake
set(_lines "")
list(APPEND _lines "# Audient Console third-party notices")
list(APPEND _lines "# Generated by the AudientConsole build. Do not edit.")
list(APPEND _lines "")

file(GLOB _notice_files "${SOURCE_DIR}/third_party/notices/*.txt" "${SOURCE_DIR}/third_party/notices/*.md")
list(SORT _notice_files)

foreach(_file IN LISTS _notice_files)
    if(EXISTS "${_file}")
        file(READ "${_file}" _content)
        list(APPEND _lines "${_content}")
        list(APPEND _lines "")
    endif()
endforeach()

string(JOIN "\n" _joined ${_lines})
file(WRITE "${OUTPUT_FILE}" "${_joined}")
message(STATUS "Generated notices: ${OUTPUT_FILE}")